### PR TITLE
SECENG-229 - Assimilate 0.1.0 to rally.

### PR DESCRIPTION
**Pull request by jeffmay**
@patrick-bohan @rcmurphy @htmldoug @PainterAndHacker 

Assimilation begins...

### CODE REVIEW

**Comment by patrick-bohan** [comment]
FAIL: The upstream code needs a license @usufruct99

**Comment by patrick-bohan** [comment]
LGTM

**Comment by jeffmay** [comment]
@patrick-bohan the license is Apache 2: https://github.com/jeffmay/play-test-ops/blob/master/LICENSE

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
Yay! Build is passing now. It was failing because of the missing JIRA ticket.

**Pull request merged**
