### PR TITLE
SECENG-229 - Assimilate 0.2.1 to rally

### PR DESCRIPTION
**Pull request by jeffmay**
@Ackertron @egprentice @htmldoug @rcmurphy @patrick-bohan @slustbader 

Depends on:
- [x] https://github.com/AudaxHealthInc/Jenkins-Job-Manager/pull/265

### CODE REVIEW

**Comment by egprentice** [comment]
Is there a way to read the rendered README or do I have to render it in my head?
LGTM

**Comment by jeffmay** [comment]
retest this please

**Comment by jeffmay** [comment]
@egprentice this is just merging the master branch of the community repo https://github.com/jeffmay/play-test-ops, you can see it rendered there on the home page.

**Comment by jeffmay** [comment]
retest this please

**Pull request merged**
